# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'DOOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for DOOS
  
    pod 'SnapKit'
    pod 'Then'
    pod 'Moya'
    pod 'HandyJSON', '5.0.0-beta.1'
    pod 'Kingfisher'
    pod 'Reusable'
    pod 'LLCycleScrollView'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'HMSegmentedControl'
    pod 'RxSwift'
    pod 'RxCocoa'
    
    
    pod 'IQKeyboardManagerSwift'
    pod 'IBAnimatable'
    pod 'FSCalendar'
    pod 'UICircularProgressRing'
    pod 'SwiftyJSON'
    pod 'SVGKit'
    pod 'Closures'
    pod 'FCUUID'
    
    pod 'EmptyDataSet-Swift'
  

    
end
